server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nmallar/spring-cloud-config-server-repository
          default-label: main
          username: nmallar
          password: ENC(4u17QMSYFWV3rcVCpfJGolWsLkqPufdH7fN9U+DoywufQI856obCmEJOAu/of0INv/F0tRSq3IisJn0F19/BsD+P8nCOVwIqwv1fOLyTqrk=)
          clone-on-start: true
      fail-fast: true

log:
  app-name: config-server

security:
  user:
    name: spring_cloud_user
    password: ENC(6IuR1fpTSJ2KgrSueZ+ZjM4jY6/Tk2+1Fed14LRKObXPhVTbSFQCkuQ+Zki/1UdH)

jasypt:
  encryptor:
    password: ${jasypt_encrypt_password}